# Build
ARG JAVA_VERSION=11-jdk-slim
FROM openjdk:${JAVA_VERSION} as BUILD

# Distribute
FROM openjdk:${JAVA_VERSION}
RUN mkdir /home/app
RUN mkdir /home/app/config
COPY config/logback-spring.xml /home/app/config/logback-spring.xml
COPY config/daemon.application.properties /home/app/config/application.properties
COPY daemon/target/service-jar-with-dependencies.jar /home/app/service.jar
CMD ["java",  "-Dlogback.configurationFile=/home/app/config/logback-spring.xml", "-jar", "/home/app/service.jar", "--CONFIG_PATH=///home/app/config/"]